//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class GymProgram
{
    String opis;
    TipPrograma tipPrograma;
    String tipProgramaS;

    public GymProgram(String opis, TipPrograma tipPrograma) 
    {
        this.opis = opis;
        this.tipPrograma = tipPrograma;
    }
    public GymProgram(String opis, String tipPrograma)
    {
        this.opis = opis;
        this.tipProgramaS = tipPrograma;
    }
    public GymProgram()
    {
        
    }
    public TipPrograma TipPrograma
	{
		get;
		set;
	}

    public String TipProgramaS
    {
        get { return tipProgramaS; }
        set { tipProgramaS = value; }
    }

    public String Opis
	{
		get;
		set;
	}

	
}

