//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class GymProgram
{
    public GymProgram()
    {
        
    }
    public TipPrograma TipPrograma
	{
		get;
		set;
	}

    public string Opis
	{
		get;
		set;
	}

}

