//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Inventar
{
    private int r;
    private int p1;
    private double p2;
    private string p3;

    public Inventar() { }

    public int Kolicina
	{
		get;
		set;
	}

    public Inventar(int kolicina)
    {
        Kolicina = kolicina;
    }

    public Inventar(int r, int p1, double p2, string p3)
    {
        // TODO: Complete member initialization
        this.r = r;
        this.p1 = p1;
        this.p2 = p2;
        this.p3 = p3;
    }

	public virtual void osvjezi()
	{
		throw new System.NotImplementedException();
	}

}

