//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Inventar
{
    public Inventar() { }

    public int Kolicina
	{
		get;
		set;
	}

    public Inventar(int kolicina)
    {
        Kolicina = kolicina;
    }

	public virtual void osvjezi()
	{
		throw new System.NotImplementedException();
	}

}

