//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Izvjestaj
{
    DateTime datumIzvjestaja;
    int iDuposlenik;
    int idIzvjestaja;
    String sadrzajIzvjestaja;

    public Izvjestaj(int id, int idUposlenika, DateTime datum, string sadrzaj)
    {
        IdIzvjestaja = id;
        IDuposlenik = idUposlenika;
        DatumIzvjestaja = datum;
        SadrzajIzvjestaja = sadrzaj;
    }

    public int IdIzvjestaja
    {
        get { return idIzvjestaja; }
        set { idIzvjestaja = value; }
    }

    public String SadrzajIzvjestaja
    {
        get { return sadrzajIzvjestaja; }
        set { sadrzajIzvjestaja = value; }
    }

    public DateTime DatumIzvjestaja
	{
        get { return datumIzvjestaja; }
        set { datumIzvjestaja = value; }
	}

    public int IDuposlenik
    {
        get { return iDuposlenik; }
        set { iDuposlenik = value; } 
    }
}

