//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Izvjestaj
{
    public Izvjestaj()
    {
        throw new System.NotImplementedException();
    }

    public string SadrzajIzvjestaja
	{
		get;
		set;
	}

    public DateTime DatumIzvjestaja
	{
		get;
		set;
	}

    public global::Uposlenik Uposlenik
    {
        get
        {
            throw new System.NotImplementedException();
        }
        set
        {
        }
    }

	


}

