//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Izvjestaj
{
    public Izvjestaj()
    {
        throw new System.NotImplementedException();
    }

    public Izvjestaj(int id, int idUposlenika, DateTime datum, string sadrzaj)
    {
        // TODO: Complete member initialization
        this.ID = id;
        this.IDuposlenik = idUposlenika;
        this.DatumIzvjestaja = datum;
        this.SadrzajIzvjestaja = sadrzaj;
    }

    public int ID { get; set; }

    public string SadrzajIzvjestaja
	{
		get;
		set;
	}

    public DateTime DatumIzvjestaja
	{
		get;
		set;
	}

    public int IDuposlenik { get; set; }
}

