//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class JednokratnaUsluga : Usluga
{

    public List<TipUsluge> OdabraneUsluge
    {
        get;
        set;
    }
    public JednokratnaUsluga()
	{
        OdabraneUsluge = new List<TipUsluge>();
	}

}

