//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Klijent : Osoba
{
    public Klijent(int id, string ime, string prezime, string spol, DateTime datumRodjenja, string kontakt, int idTrenera=0, int idNutricioniste=0) 
        : base(id, ime, prezime, spol, datumRodjenja, kontakt)
    {
        IDtrenera = idTrenera;
        IDnutricioniste = idNutricioniste;
    }

    public int IDtrenera { get; set; }

    public int IDnutricioniste { get; set; }
}

