//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Nutricionista : Uposlenik
{
    public Nutricionista() { }

	public virtual void azurirajProgram()
	{
		throw new System.NotImplementedException();
	}

	public virtual PrehrambeniProgram noviProgram()
	{
		throw new System.NotImplementedException();
	}

}

