//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Oprema : Inventar
{
    public Oprema() { }
    string tipopremes;
    public Oprema(int id, int kolicina, double cijena, string tipOpreme) : base(kolicina)
    {
        ID = id;
        if (tipOpreme == "Bandaze") TipOpreme = TipOpreme.Bandaze;
        if (tipOpreme == "Flasa") TipOpreme = TipOpreme.Flasa;
        if (tipOpreme == "Peskir") TipOpreme = TipOpreme.Peskir;
        if (tipOpreme == "Pojas") TipOpreme = TipOpreme.Pojas;
        if (tipOpreme == "Rukavice") TipOpreme = TipOpreme.Rukavice;
        if (tipOpreme == "Sorts") TipOpreme = TipOpreme.Sorts;
        if (tipOpreme == "Tene") TipOpreme = TipOpreme.Tene;
        CijenaNajama = cijena;
        tipopremes = tipOpreme;
    }

    public int ID { get; set; }

    public TipOpreme TipOpreme
	{
		get;
		set;
	}

    public double CijenaNajama
	{
		get;
		set;
	}

    
    public string TipOpremeS
    {
        get { return tipopremes; }
        set {tipopremes = value; }
    }
    
}

