//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Oprema : Inventar
{
    public Oprema() { }
    public TipOpreme TipOpreme
	{
		get;
		set;
	}

    public decimal CijenaNajama
	{
		get;
		set;
	}

}

