//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Oprema : Inventar
{
    TipOpreme tipOpreme;
    String tipopremes;
    Decimal cijenaNajama;
    int idOpreme;
    /*public Oprema(int id, int kolicina, Decimal cijena, string tipOpreme) : base(kolicina)
    {
        IdOpreme = id;
        if (tipOpreme == "Bandaze") TipOpreme = TipOpreme.Bandaze;
        if (tipOpreme == "Flasa") TipOpreme = TipOpreme.Flasa;
        if (tipOpreme == "Peskir") TipOpreme = TipOpreme.Peskir;
        if (tipOpreme == "Pojas") TipOpreme = TipOpreme.Pojas;
        if (tipOpreme == "Rukavice") TipOpreme = TipOpreme.Rukavice;
        if (tipOpreme == "Sorts") TipOpreme = TipOpreme.Sorts;
        if (tipOpreme == "Tene") TipOpreme = TipOpreme.Tene;
        CijenaNajama = cijena;
        tipopremes = tipOpreme;
    }*/
    public Oprema(int id, int kolicina, Decimal cijena, String tipOpreme)
        : base(kolicina)
    {
        IdOpreme = id;
        CijenaNajama = cijena;
        TipOpremeS = tipOpreme;
    }
    public int IdOpreme
    {
        get { return idOpreme; }
        set { idOpreme = value; }
    }

    public TipOpreme TipOpreme
	{
        get { return tipOpreme; }
        set { tipOpreme = value; }
	}

    public Decimal CijenaNajama
    {
        get { return cijenaNajama; }
        set { cijenaNajama = value; }
    }
  
    public String TipOpremeS
    {
        get { return tipopremes; }
        set {tipopremes = value; }
    }
    
}

