//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PrehrambeniProgram : GymProgram
{
    private int p1;
    private string p2;
    private string p3;
    private string p4;

	
    public PrehrambeniProgram()
	{
		
	}

    public PrehrambeniProgram(int p1, string p2, string p3, string p4) // UREDITI PO NAMJENI (FROM BASE ITD)
    {
        // TODO: Complete member initialization
        this.p1 = p1;
        this.p2 = p2;
        this.p3 = p3;
        this.p4 = p4;
    }

    public string Obroci
    {
        get;
        set;
    }

    int ID;

    public int ID1
    {
        get { return ID; }
        set { ID = value; }
    }
}

