//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PrehrambeniProgram : GymProgram
{
    int idPrehrambeniProgram;
    public PrehrambeniProgram(int idWorkoutPrograma, String opis, String tipPrograma, String obroci) :
            base(opis, tipPrograma)
        {
            IdPrehrambeniProgram = idWorkoutPrograma;
            Obroci = obroci;
        }

    public int IdPrehrambeniProgram
    {
        get { return idPrehrambeniProgram; }
        set { idPrehrambeniProgram = value; }
    }
    public string Obroci
    {
        get;
        set;
    }
}

