//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Prostorija
{
    public Prostorija() { }

    public Prostorija(int p1, string p2, string p3, string p4) // UREDITI PO NAMJENI (ATRIBUTI)
    {
        // TODO: Complete member initialization
        this.p1 = p1;
        this.p2 = p2;
        this.p3 = p3;
        this.p4 = p4;
    }
    int id;
    private int p1;
    private string p2;
    private string p3;
    private string p4;

    public int Id
    {
        get { return id; }
        set { id = value; }
    }
    public TipProstorije NazivProstorije
	{
		get;
		set;
	}

    public bool Dostupnost
	{
		get;
		set;
    }

    public List<Inventar> Inventar
    {
        get
        {
            throw new System.NotImplementedException();
        }
        set
        {
        }
    }

}

