//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Prostorija
{
    public Prostorija() { }
    public TipProstorije NazivProstorije
	{
		get;
		set;
	}

    public bool Dostupnost
	{
		get;
		set;
    }

    public List<Inventar> Inventar
    {
        get
        {
            throw new System.NotImplementedException();
        }
        set
        {
        }
    }

}

