//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Suplement : Inventar
{
    int idSuplementa;
    String tipSuplementaS;
    Decimal cijena;

    public Suplement(int id, int kolicina, Decimal cijena, String tipSuplementa):base(kolicina)
    {
        IdSuplementa = id;
        TipSuplementaS = tipSuplementa;
        Cijena = cijena;
    }

    public override string ToString()
    {
        return Convert.ToString(TipSuplementa);
    }

    public int IdSuplementa
    {
        get { return idSuplementa; }
        set { idSuplementa = value; }
    }
    public String TipSuplementaS
    {
        get { return tipSuplementaS; }
        set { tipSuplementaS = value; }
    }
    public Decimal Cijena
	{
        get { return cijena; }
        set { cijena = value; }
	}
    public TipSuplementa TipSuplementa
    {
        get;
        set;
    }
}

