//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Suplement : Inventar
{
    int idSuplementa;
    TipSuplementa tipSuplementa;
    String tipSuplementaS;
    Decimal cijena;
    
    public Suplement() { }

    public Suplement(int id, TipSuplementa tipSuplementa, Decimal cijena)
    {
        // TODO: Complete member initialization
        this.idSuplementa = id;
        this.tipSuplementa = tipSuplementa;
        this.cijena = cijena;
    }

    public Suplement(int id, String tipSuplementa, Decimal cijena)
    {
        // TODO: Complete member initialization
        this.idSuplementa = id;
        this.tipSuplementaS = tipSuplementa;
        this.cijena = cijena;
    }

    public int IdSuplementa
    {
        get;
        set;
    }

    public TipSuplementa TipSuplementa
	{
		get;
		set;
	}

    public Decimal Cijena
	{
		get;
		set;
	}

}

