//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

    public class Uposlenik : Osoba
    {
        String zaposlenjeS;
        String sifra;
        int idUposlenika;

        public Uposlenik()
        {

        }


        public Uposlenik(int idUposlenika, String ime, String prezime, String spol, DateTime datumRodjenja,
            DateTime datumZaposlenja, Decimal plata, String kontakt, String zaposlenje, String sifra) :
            base(idUposlenika, ime, prezime, spol, datumRodjenja, kontakt)
        {
            Plata = plata;
            DatumZaposlenja = datumZaposlenja;
            ZaposlenjeS = zaposlenje;
            this.sifra = sifra;
        }
        public decimal Plata
        {
            get;
            set;
        }

        public int IdUposlenika
        {
            get { return idUposlenika; }
            set { idUposlenika = value; }
        }

        public String Sifra
        {
            get { return sifra; }
            set { sifra = value; }
        }

        public String ZaposlenjeS
        {
            get { return zaposlenjeS; }
            set { zaposlenjeS = value; }
        }

        public DateTime DatumZaposlenja
        {
            get;
            set;
        }

        public TipZaposlenja Zaposlenje
        {
            get;
            set;
        }

        public virtual Izvjestaj kreirajIzvjestaj()
        {
            throw new System.NotImplementedException();
        }

        public virtual void azurirajPodatke()
        {
            throw new System.NotImplementedException();
        }
        public override string ToString()
        {
            return ID + " " + Ime + " " + Prezime + Environment.NewLine + ZaposlenjeS;
        }

    }

