//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Usluga
{
    public Usluga() { }
    public decimal Cijena
	{
		get;
		set;
    }

    public global::Prostorija Prostorija
    {
        get
        {
            throw new System.NotImplementedException();
        }
        set
        {
        }
    }


	public virtual decimal obracunajCijenu()
	{
		throw new System.NotImplementedException();
	}
}

