//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class WorkoutProgram : GymProgram
{
    int idWorkoutPrograma;
    String vjezbe;
    public WorkoutProgram(int idWorkoutPrograma, String opis, TipPrograma tipPrograma, String vjezbe) :
        base(opis, tipPrograma) 
    {
        this.idWorkoutPrograma = idWorkoutPrograma;
        this.vjezbe = vjezbe;
    }
    public WorkoutProgram(int idWorkoutPrograma, String opis, String tipPrograma, String vjezbe) :
        base(opis, tipPrograma)
    {
        this.idWorkoutPrograma = idWorkoutPrograma;
        this.vjezbe = vjezbe;
    }
    public WorkoutProgram()
	{
        
    }

    public int IdWorkoutPrograma
    {
        get { return idWorkoutPrograma; }
        set { idWorkoutPrograma = value; }
    }

    public String Vjezbe
    {
        get;
        set;
    }
	
    

}

