//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Administrator : Osoba
{
	public List<Izvjestaj> Izvjestaji
	{
		get;
		set;
    }


	public virtual void registrujUposlenika(Uposlenik uposlenik)
	{
		throw new System.NotImplementedException();
	}

	public virtual void obradiIzvjestaj()
	{
		throw new System.NotImplementedException();
	}

}

