//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Inventar
{
    public virtual Inventar(){

    }
	private int kolicina
	{
		get;
		set;
	}

	

	public virtual void osvjezi()
	{
		throw new System.NotImplementedException();
	}

}

