//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class JednokratnaUsluga : Usluga
{
    List<TipUsluge> odabraneUsluge;

    public List<TipUsluge> OdabraneUsluge
    {
        get { return odabraneUsluge; }
        set { odabraneUsluge = value; }
    }
    public JednokratnaUsluga()
	{
        odabraneUsluge = new List<TipUsluge>();
	}


}

