//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Klijent : Osoba
{
	private double tezina
	{
		get;
		set;
	}

	private double visina
	{
		get;
		set;
	}

	private string komentar
	{
		get;
		set;
	}

}

