//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PrehrambeniProgram : Program
{
    private string[] obroci;
	
    public virtual void PrehrambeniProgram()
	{
		obroci=new string[7];
	}

}

