//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Prostorija
{
    public Prostorija() { }
	private TipProstorije nazivProstorije
	{
		get;
		set;
	}

	private bool dostupnost
	{
		get;
		set;
	}

	public virtual IEnumerable<Inventar> Inventar
	{
		get;
		set;
	}

}

