//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Sprava : Inventar
{
    public Sprava() { }
    public TipSprave TipSprave
	{
		get;
		set;
	}

    public int Starost
	{
		get;
		set;
	}

}

