//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Trener : Uposlenik
{
    public Trener() { }
	private string komentar
	{
		get;
		set;
	}

	public virtual IEnumerable<WorkoutProgram> WorkoutProgram
	{
		get;
		set;
	}

	public virtual WorkoutProgram noviProgram()
	{
		throw new System.NotImplementedException();
	}

	public virtual void azurirajProgram()
	{
		throw new System.NotImplementedException();
	}

}

