//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Uposlenik : Osoba
{
    public Uposlenik() { }
    public decimal Plata
	{
		get;
		set;
	}

    public DateTime DatumZaposlenja
	{
		get;
		set;
    }

	

	public virtual Izvjestaj kreirajIzvjestaj()
	{
		throw new System.NotImplementedException();
	}

	public virtual void azurirajPodatke()
	{
		throw new System.NotImplementedException();
	}

}

