//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Usluga
{
    public Usluga() { }
	private decimal cijena
	{
		get;
		set;
	}

	public virtual IEnumerable<Prostorija> Prostorija
	{
		get;
		set;
	}


	public virtual decimal obracunajCijenu()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Usluga()
	{
		throw new System.NotImplementedException();
	}

}

